### ISSUE TITLE
Filesystem error on partial zones.

### ISSUE THREAD

**Issue by CRCinAU** [perryflynn/nsupdate-interactive#1]
Hi mate,

After having FreeIPA drop all my DNSSEC keys, I rolled a new master DNS server using bind for DNS - and found this tool just brilliant compared to having to edit the bind files directly. Using AFXR and nsupdate is a perfect way to do this.

I did find a problem with classless delegations - where there is a / in the zone name. It seems to treat it as a file delimiter for saving the temporary files.

An example of the zone file configuration in named.conf is:
```
zone "16/28.99.172.202.in-addr.arpa." in {
	type		master;
	file		"master/99.172.202.in-addr.arpa";
};
```

This is for delegation of a /28 worth of IP space from my ISPs DNS server.

The error message shown is:
```
Traceback (most recent call last):
  File "/root/nsupdate-interactive/src/nsupdate-interactive.py", line 192, in <module>
    main()
  File "/root/nsupdate-interactive/src/nsupdate-interactive.py", line 125, in main
    formatter.save(filename.format(version), records)
  File "/root/nsupdate-interactive/src/zoneutils/zonefileformatter.py", line 59, in save
    with open(file, 'w+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'nsupdate_127.0.0.1_16/28.99.172.202.in-addr.arpa._20220510T181137Z.org.db'
```

Looks like it might need some sanity checking on the filenames before a save - maybe substituting the / for a different character only for the file being saved to disk?

**Comment by CRCinAU** [comment]
This seems to work as a quick-n-dirty hack:

```
diff --git a/src/nsupdate-interactive.py b/src/nsupdate-interactive.py
index 697ccb2..d3dea9b 100755
--- a/src/nsupdate-interactive.py
+++ b/src/nsupdate-interactive.py
@@ -90,6 +90,7 @@ def main():
     # base filename
     ts = datetime.datetime.now().strftime('%Y%m%dT%H%M%S')+'Z'
     filename = 'nsupdate_'+args.dnsserver+'_'+args.zone+'_'+ts+'.{0}.db'
+    filename = filename.replace('/', '_')
 
     # get zone records by calling dig
     digstr = utils.dig_zonetransfer(args.dnsserver, hmackey, args.zone)
```

**Comment by perryflynn** [comment]
Hi,

the components of the filenames will now sanitized in e7501f0d72a1dd2719fe575f4f04979853f14051.

Could you test that, please?

Thanks
Christian

**Comment by CRCinAU** [comment]
Can confirm, filenames now seem to be sanitised correclty.
