### ISSUE TITLE
RFE: Ability to ignore record types

### ISSUE THREAD

**Issue by CRCinAU** [perryflynn/nsupdate-interactive#2]
When using this interface to edit zone files, the AXFR will pull in RRSIG and NSEC records -  which probably shouldn't be edited manually, but also take up a hell of a lot of space.

It would be nice to see an option to build a list of record types that are ignored and not shown.

**Comment by perryflynn** [comment]
Hi,

I implemented a mechanic to ignore RR types in e7501f0d72a1dd2719fe575f4f04979853f14051.

Could you test that?

Thanks
Christian

**Comment by CRCinAU** [comment]
Hi mate,

So, interesting part - when I edit a zone file now, make no changes but quit, I see:

```
zone <zonefile>/IN: CDS/CDNSKEY consistency checks failed
zone <zonefile>/IN: not loaded due to errors.
```

I'm not quite sure what this is - or why its failing....

**Comment by perryflynn** [comment]
I use `named-checkzone` the tool from bind9 for checking the zone file for syntax errors. Maybe it breaks because it contains a CDS/CDNSKEY record but not the other dnssec records? could you add these record types to the ignore list?

I havn't a zone to test this. My dnssec zones don't have CDS/CDNSKEY records.

**Comment by CRCinAU** [comment]
Yeah - that seems to work ok if I ignore them manually... I wrote a quick wrapper bash script that saves me typing more stuff:

```
#!/bin/bash

export HMAC=hmac-sha256:local-ddns:$(grep secret /run/named/session.key | awk -F'"' '{ print $2 }')

IGNORE=""
for i in CDS CDNSKEY DNSKEY RRSIG NSEC TYPE65534; do
	IGNORE="$IGNORE --ignore-rrtype $i "
done

~/nsupdate-interactive/src/nsupdate-interactive.py --dnsserver 127.0.0.1 --zone $1 $IGNORE
rm -f nsupdate*.db
```

That seems to update fine.

**Comment by perryflynn** [comment]
Ok, I added CDS/CDNSKEY to the default ignore list as well:

```py
DEFAULT_IGNORE_RRTYPES = [ 'DNSKEY', 'RRSIG', 'NSEC', 'TYPE65534', 'CDS', 'CDNSKEY' ]
```

**Comment by CRCinAU** [comment]
Awesome, thanks - that should be enough to fix this too :)

**Comment by CRCinAU** [comment]
@perryflynn - Oh, actually - I lie.

It seems the +x attribute has been dropped from `nsupdate-interactive.py` as well.
